development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: testdb
  pool: 5
  username: postgres
  password: tsb1234

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: testdb
  pool: 5
  username: postgres
  password: tsb1234