development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: postgresql
  password: tsb1234

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: postgresql
  password: tsb1234